name: Upload to PyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: Install dependencies
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          # If requirements.txt exists, install from it
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install the package from setup.py
      
      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: https://upload.pypi.org/legacy/
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
